import { afterEach, describe, expect, test } from "bun:test";
import { randomUUID } from "node:crypto";
import { mkdir, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { file, write } from "bun";
import { addVersionHeaderMigration } from "./add-version-header.migration";

const createTempDir = () =>
    join(tmpdir(), `scaffoldizr-add-version-header-test-${randomUUID()}`);

describe("addVersionHeaderMigration.apply", () => {
    let testDir: string;

    afterEach(async () => {
        await rm(testDir, { recursive: true, force: true });
    });

    test("dryRun=true on workspace without header: returns applied=true and does not modify file", async () => {
        testDir = createTempDir();
        await mkdir(testDir, { recursive: true });
        const workspaceDslPath = resolve(testDir, "workspace.dsl");
        const originalContent = 'workspace "Test" {}';
        await write(workspaceDslPath, originalContent);

        const result = await addVersionHeaderMigration.apply(
            testDir,
            testDir,
            true,
        );

        expect(result.applied).toBe(true);
        expect(result.filesChanged).toEqual(["workspace.dsl"]);
        expect(await file(workspaceDslPath).text()).toBe(originalContent);
    });

    test("dryRun=false on workspace without header: returns applied=true and stamps header", async () => {
        testDir = createTempDir();
        await mkdir(testDir, { recursive: true });
        const workspaceDslPath = resolve(testDir, "workspace.dsl");
        await write(workspaceDslPath, 'workspace "Test" {}');

        const result = await addVersionHeaderMigration.apply(
            testDir,
            testDir,
            false,
        );

        expect(result.applied).toBe(true);
        expect(result.filesChanged).toEqual(["workspace.dsl"]);
        expect(await file(workspaceDslPath).text()).toMatch(
            /^# Generated by Scaffoldizr v/,
        );
    });

    test("dryRun=false on workspace with existing header: returns applied=false and skips", async () => {
        testDir = createTempDir();
        await mkdir(testDir, { recursive: true });
        const workspaceDslPath = resolve(testDir, "workspace.dsl");
        await write(
            workspaceDslPath,
            '# Generated by Scaffoldizr v0.10.0\nworkspace "Test" {}',
        );

        const result = await addVersionHeaderMigration.apply(
            testDir,
            testDir,
            false,
        );

        expect(result.applied).toBe(false);
        expect(result.filesChanged).toEqual([]);
    });
});
