import { afterEach, describe, expect, test } from "bun:test";
import { randomUUID } from "node:crypto";
import { mkdir, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { file, write } from "bun";
import pkg from "../../package.json";
import { isNewerVersion } from "../utils/version";
import { getPendingMigrations, runMigrations } from "./index";
import { migrations } from "./registry";

const createTempDir = () =>
    join(tmpdir(), `scaffoldizr-migrations-test-${randomUUID()}`);

describe("getPendingMigrations", () => {
    test("no migration toVersion exceeds current tool version", () => {
        const futureMigrations = migrations.filter((m) =>
            isNewerVersion(m.toVersion, pkg.version),
        );
        expect(futureMigrations).toEqual([]);
    });

    test("returns empty array when workspace is at current tool version", () => {
        const result = getPendingMigrations(pkg.version);
        expect(result).toEqual([]);
    });

    test("returns all migrations when workspace is at 0.0.0", () => {
        const result = getPendingMigrations("0.0.0");
        expect(result).toHaveLength(migrations.length);
    });

    test("returns empty array when currentVersion is higher than all migrations", () => {
        const result = getPendingMigrations("99.0.0");
        expect(result).toEqual([]);
    });
});

describe("runMigrations", () => {
    let testDir: string;

    afterEach(async () => {
        await rm(testDir, { recursive: true, force: true });
    });

    test("applies migrations and writes version header when workspace has no version", async () => {
        testDir = createTempDir();
        await mkdir(testDir, { recursive: true });
        await mkdir(resolve(testDir, "scripts"), { recursive: true });

        const workspaceDslPath = resolve(testDir, "workspace.dsl");
        await write(workspaceDslPath, 'workspace "Test" {}');

        await runMigrations(testDir, testDir, false);

        const updatedContent = await file(workspaceDslPath).text();
        expect(updatedContent).toMatch(/^# Generated by Scaffoldizr v/);
    });

    test("handles no-pending migration path based on tool and workspace versions", async () => {
        testDir = createTempDir();
        await mkdir(testDir, { recursive: true });
        await mkdir(resolve(testDir, "scripts"), { recursive: true });

        const workspaceDslPath = resolve(testDir, "workspace.dsl");
        await write(
            workspaceDslPath,
            `# Generated by Scaffoldizr v${pkg.version}\nworkspace "Test" {}`,
        );

        const originalLog = console.log;
        const logMessages: string[] = [];
        console.log = (...args: unknown[]) => {
            logMessages.push(args.join(" "));
        };

        try {
            await runMigrations(testDir, testDir, false);
        } finally {
            console.log = originalLog;
        }

        const allOutput = logMessages.join("\n");
        const migratedContent = await file(workspaceDslPath).text();

        expect(allOutput).toContain("already up to date");
        expect(migratedContent).toContain(
            `# Generated by Scaffoldizr v${pkg.version}`,
        );
    });

    test("logs already up to date when workspace version equals current tool version", async () => {
        testDir = createTempDir();
        await mkdir(testDir, { recursive: true });
        await mkdir(resolve(testDir, "scripts"), { recursive: true });

        const workspaceDslPath = resolve(testDir, "workspace.dsl");
        await write(
            workspaceDslPath,
            `# Generated by Scaffoldizr v${pkg.version}\nworkspace "Test" {}`,
        );

        const originalLog = console.log;
        const logMessages: string[] = [];
        console.log = (...args: unknown[]) => {
            logMessages.push(args.join(" "));
        };

        try {
            await runMigrations(testDir, testDir, false);
        } finally {
            console.log = originalLog;
        }

        expect(logMessages.join("\n")).toContain("already up to date");
    });

    test("dry-run previews version header update without writing workspace.dsl", async () => {
        testDir = createTempDir();
        await mkdir(testDir, { recursive: true });
        await mkdir(resolve(testDir, "scripts"), { recursive: true });

        const workspaceDslPath = resolve(testDir, "workspace.dsl");
        const initialWorkspaceContent = 'workspace "Test" {}';
        await write(workspaceDslPath, initialWorkspaceContent);

        const originalLog = console.log;
        const logMessages: string[] = [];
        console.log = (...args: unknown[]) => {
            logMessages.push(args.join(" "));
        };

        try {
            await runMigrations(testDir, testDir, true);
        } finally {
            console.log = originalLog;
        }

        expect(logMessages.join("\n")).toContain("[DRY RUN]");
        expect(await file(workspaceDslPath).text()).toBe(
            initialWorkspaceContent,
        );
    });
});
