import { afterEach, describe, expect, test } from "bun:test";
import { randomUUID } from "node:crypto";
import { mkdir, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { file, write } from "bun";
import { getPendingMigrations, runMigrations } from "./index";

const createTempDir = () =>
    join(tmpdir(), `scaffoldizr-migrations-test-${randomUUID()}`);

describe("getPendingMigrations", () => {
    test("returns empty array when currentVersion equals migration toVersion", () => {
        const result = getPendingMigrations("0.10.0");
        expect(result).toEqual([]);
    });

    test("returns regenerate-scripts migration when currentVersion is 0.0.0", () => {
        const result = getPendingMigrations("0.0.0");
        expect(result).toHaveLength(1);
        expect(result[0].toVersion).toBe("0.10.0");
    });

    test("returns empty array when currentVersion is higher than all migrations", () => {
        const result = getPendingMigrations("99.0.0");
        expect(result).toEqual([]);
    });
});

describe("runMigrations", () => {
    let testDir: string;

    afterEach(async () => {
        await rm(testDir, { recursive: true, force: true });
    });

    test("applies migrations and writes version header when workspace has no version", async () => {
        testDir = createTempDir();
        await mkdir(testDir, { recursive: true });
        await mkdir(resolve(testDir, "scripts"), { recursive: true });

        const workspaceDslPath = resolve(testDir, "workspace.dsl");
        await write(workspaceDslPath, 'workspace "Test" {}');

        await runMigrations(testDir, testDir, false);

        const updatedContent = await file(workspaceDslPath).text();
        expect(updatedContent).toMatch(/^# Generated by Scaffoldizr v/);
    });

    test("logs already up to date when workspace version equals migration toVersion", async () => {
        testDir = createTempDir();
        await mkdir(testDir, { recursive: true });
        await mkdir(resolve(testDir, "scripts"), { recursive: true });

        const workspaceDslPath = resolve(testDir, "workspace.dsl");
        await write(
            workspaceDslPath,
            '# Generated by Scaffoldizr v0.10.0\nworkspace "Test" {}',
        );

        const originalLog = console.log;
        const logMessages: string[] = [];
        console.log = (...args: unknown[]) => {
            logMessages.push(args.join(" "));
        };

        try {
            await runMigrations(testDir, testDir, true);
        } finally {
            console.log = originalLog;
        }

        const allOutput = logMessages.join("\n");
        expect(allOutput).toContain("already up to date");
    });
});
