import { afterAll, describe, expect, test } from "bun:test";
import { join } from "node:path";
import { $, file, spawn, write } from "bun";
import { createWorkspaceFromCLI } from "../test/workspace";

const TMP_FOLDER = process.env.TMP_FOLDER || "/tmp";

describe("e2e: scfz migrate", () => {
    const folder = join(
        TMP_FOLDER,
        `test-${(1000 + Math.ceil(Math.random() * 1000)).toString(16)}`,
    );

    afterAll(async () => {
        await $`rm -rf ${folder}`;
    });

    test("should stamp version header on a workspace without one", async () => {
        await createWorkspaceFromCLI(folder, "landscape");

        const workspaceDslPath = `${folder}/architecture/workspace.dsl`;
        const content = await file(workspaceDslPath).text();
        const strippedContent = content.replace(
            /^# Generated by Scaffoldizr v[^\n]*\n/,
            "",
        );
        await write(workspaceDslPath, strippedContent);

        const proc = spawn(["dist/scfz", "migrate", "--dest", folder]);
        await proc.exited;

        expect(proc.exitCode).toBe(0);

        const updatedContent = await file(workspaceDslPath).text();
        expect(updatedContent).toMatch(/^# Generated by Scaffoldizr v/);
    });

    test("should preview changes without writing in dry-run mode", async () => {
        const dryFolder = join(
            TMP_FOLDER,
            `test-${(1000 + Math.ceil(Math.random() * 1000)).toString(16)}`,
        );

        try {
            await createWorkspaceFromCLI(dryFolder, "landscape");

            const workspaceDslPath = `${dryFolder}/architecture/workspace.dsl`;
            const content = await file(workspaceDslPath).text();
            const strippedContent = content.replace(
                /^# Generated by Scaffoldizr v[^\n]*\n/,
                "",
            );
            await write(workspaceDslPath, strippedContent);

            const proc = spawn([
                "dist/scfz",
                "migrate",
                "--dry-run",
                "--dest",
                dryFolder,
            ]);
            const stdout = await new Response(proc.stdout).text();
            await proc.exited;

            expect(proc.exitCode).toBe(0);
            expect(stdout).toContain("DRY RUN");

            const afterContent = await file(workspaceDslPath).text();
            expect(afterContent).toBe(strippedContent);
        } finally {
            await $`rm -rf ${dryFolder}`;
        }
    });
});
