import { file, write } from "bun";
import chalk from "chalk";

export async function getWorkspaceVersion(
    workspaceDslPath: string,
): Promise<string> {
    try {
        const content = await file(workspaceDslPath).text();
        const match = content.match(
            /^# Generated by Scaffoldizr v(\d+\.\d+\.\d+[^\n]*)/m,
        );
        return match ? match[1] : "0.0.0";
    } catch {
        return "0.0.0";
    }
}

export async function updateWorkspaceVersion(
    workspaceDslPath: string,
    newVersion: string,
    dryRun: boolean,
): Promise<void> {
    if (dryRun) {
        console.log(
            chalk.gray(
                `[DRY RUN]: Would update workspace version header to v${newVersion}`,
            ),
        );
        return;
    }

    const content = await file(workspaceDslPath).text();
    const versionHeaderRegex = /^# Generated by Scaffoldizr v[^\n]*/m;
    const updatedContent = versionHeaderRegex.test(content)
        ? content.replace(
              versionHeaderRegex,
              `# Generated by Scaffoldizr v${newVersion}`,
          )
        : `# Generated by Scaffoldizr v${newVersion}\n${content}`;

    await write(workspaceDslPath, updatedContent);
    console.log(
        chalk.gray(`[UPDATED]: workspace.dsl version header → v${newVersion}`),
    );
}
