import { afterEach, describe, expect, test } from "bun:test";
import { randomUUID } from "node:crypto";
import { rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { write } from "bun";
import {
    getWorkspaceVersion,
    updateWorkspaceVersion,
} from "./workspace-version";

const testArtifactsRootFolderPath = join(
    tmpdir(),
    "scaffoldizr-workspace-version-test",
);
const createdFilePaths: string[] = [];

const createFileWithContent = async (content: string): Promise<string> => {
    const filePath = join(testArtifactsRootFolderPath, `${randomUUID()}.dsl`);
    await write(filePath, content);
    createdFilePaths.push(filePath);
    return filePath;
};

afterEach(async () => {
    await Promise.all(
        createdFilePaths.splice(0).map((p) => rm(p, { force: true })),
    );
    await rm(testArtifactsRootFolderPath, { recursive: true, force: true });
});

describe("getWorkspaceVersion", () => {
    test("returns version from file with header", async () => {
        const filePath = await createFileWithContent(
            "# Generated by Scaffoldizr v0.10.0\nworkspace {}",
        );
        const version = await getWorkspaceVersion(filePath);
        expect(version).toBe("0.10.0");
    });

    test("returns 0.0.0 for file without header", async () => {
        const filePath = await createFileWithContent("workspace {}");
        const version = await getWorkspaceVersion(filePath);
        expect(version).toBe("0.0.0");
    });

    test("returns 0.0.0 for non-existent file", async () => {
        const version = await getWorkspaceVersion(
            "/non/existent/path/workspace.dsl",
        );
        expect(version).toBe("0.0.0");
    });
});

describe("updateWorkspaceVersion", () => {
    test("dryRun=true leaves file unchanged", async () => {
        const originalContent = "workspace {}";
        const filePath = await createFileWithContent(originalContent);
        await updateWorkspaceVersion(filePath, "1.0.0", true);
        const content = await import("bun").then((bun) =>
            bun.file(filePath).text(),
        );
        expect(content).toBe(originalContent);
    });

    test("replaces existing header", async () => {
        const filePath = await createFileWithContent(
            "# Generated by Scaffoldizr v0.9.0\nworkspace {}",
        );
        await updateWorkspaceVersion(filePath, "1.0.0", false);
        const content = await import("bun").then((bun) =>
            bun.file(filePath).text(),
        );
        expect(content).toBe("# Generated by Scaffoldizr v1.0.0\nworkspace {}");
    });

    test("prepends header when none exists", async () => {
        const originalContent = "workspace {}";
        const filePath = await createFileWithContent(originalContent);
        await updateWorkspaceVersion(filePath, "1.0.0", false);
        const content = await import("bun").then((bun) =>
            bun.file(filePath).text(),
        );
        expect(content).toBe(
            `# Generated by Scaffoldizr v1.0.0\n${originalContent}`,
        );
    });
});
