plugins:
  - jekyll-remote-include

collections:
  adrs:
    output: true

exclude:
  - _adrs

theme: jekyll-theme-hacker

# Theme variables
title: "Scaffoldizr: Scaffolding to create Structurizr Workspaces"
description: Opinionated TypeScript/Bun Scaffolding Tool for creating Structurizr DSL Documentations