source 'https://rubygems.org'
gem 'jekyll'
gem "jekyll-theme-hacker", "~> 0.2.0"
gem "webrick", "~> 1.8"
gem "kramdown-parser-gfm", "~> 1.1"

group :jekyll_plugins do
    gem 'jekyll-remote-include', :github => 'netrics/jekyll-remote-include'
end
