name: Build, Test and Release

on: push

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-tags: true
      - name: Mise Tools install
        uses: jdx/mise-action@v2
        with:
          version: 2024.3.1
          install: true
          cache: true
          experimental: true
      - name: Test
        run: |
          bun install
          bun test:ci
      - name: See Git tags
        run: git tag --list
      - name: Create binary and release files # FIXME: Bun issue with bin path
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          mkdir ./dist
          bun build ./lib/main.ts --compile --outfile ./dist/scfz
          tar -czvf ./dist/scfz.tar.gz ./lib/scfz
          ./lib/scfz --version
          bun changelog --file dist/changelog.txt --tag $(git tag --list --sort=v:refname | grep -v beta | tail -n 1)
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: true
          prerelease: ${{contains(github.ref, '-beta')}}
          body_path: ./dist/changelog.txt
          files: | # FIXME: Bun issue with bin path
            ./lib/scfz
            ./dist/scfz.tar.gz
            LICENSE