name: Test

on:
  workflow_call:
  pull_request:
    branches:
      - develop
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Mise Tools install
        uses: jdx/mise-action@v2
        with:
          version: 2024.3.1
          install: true
          cache: true
          experimental: true
      - name: Test
        run: |
          bun install
          bun test:ci
