name: Test and build

on:
  workflow_call:
  workflow_dispatch:
jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          fetch-tags: true
      - name: Mise Tools install
        uses: jdx/mise-action@v4
        with:
          version: 2025.11.10
          install: true
          cache: true
          experimental: true
      - name: Test
        run: |
          mise use bun@1.3.3
          bun install
          bun test:ci
  output-version:
    needs: test
    if: always()
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.extract.outputs.version }}
    steps:
      - name: Extract version from tag
        id: extract
        run: |
          if [[ "${{ github.ref }}" == refs/tags/v* ]]; then
            version=$(echo "${{ github.ref }}" | sed -e s%refs/tags/v%%)
          else
            version=$(echo "${{ github.ref }}" | sed -e 's|refs/heads/||')
          fi
          echo "version=$version" >> "$GITHUB_OUTPUT"
          echo "$version" > TESTED_VERSION.txt
          cat TESTED_VERSION.txt
      - uses: actions/upload-artifact@v6
        with:
          name: TESTED_VERSION
          path: ./TESTED_VERSION.txt
          if-no-files-found: error
  build:
    needs: output-version
    if: always()
    name: build-${{matrix.name}}
    runs-on: ${{matrix.runs-on}}
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu
            name: linux-x64
            target: x86_64-unknown-linux-gnu
            runs-on: ubuntu-latest
          - os: ubuntu
            name: linux-arm64
            target: aarch64-unknown-linux-gnu
            runs-on: ubuntu-latest
          - os: macos
            name: darwin-x64
            target: x86_64-apple-darwin
            runs-on: macos-latest
          - os: macos
            name: darwin-arm64
            target: aarch64-apple-darwin
            runs-on: macos-latest
          - os: windows
            name: win-x64
            target: x86_64-ms-windows
            runs-on: windows-latest
    steps:
      - uses: actions/checkout@v6
      - name: Mise Tools install
        uses: jdx/mise-action@v4
        if: ${{ matrix.os != 'windows' }}
        with:
          version: 2025.11.10
          install: true
          cache: true
          experimental: true
      - run: mise use bun@1.3.3
        if: ${{ matrix.os != 'windows' }}
      - name: Choco Tools Install
        run: |
          choco install jq --version 1.7.1
          choco install bun --version 1.3.3
        if: ${{ matrix.os == 'windows' }}
      - run: bun install --ignore-scripts
      - name: Write version to package.json
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          version="${{ needs.output-version.outputs.version }}"
          jq --indent 4 --arg version "$version" '.version = $version' package.json > package.json.tmp
          mv package.json.tmp package.json
      - name: Create binary and release files
        run: |
          jq -r '.version' package.json
          mkdir -p ./dist/${{ matrix.name }}
          bun build ./lib/main.ts --compile --outfile ./dist/${{ matrix.name }}/scfz
          ./dist/${{ matrix.name }}/scfz --version
          cd ./dist
          tar -czvf scfz-${{ matrix.name }}.tar.gz ./${{ matrix.name }}
          cd ..
          # TODO: Checksums
      - uses: actions/upload-artifact@v6
        with:
          name: tarball-${{matrix.target}}
          path: |
            ./dist/scfz-*.tar.gz
          if-no-files-found: error
